### PR TITLE
Remove family provider migrator docs

### PR DESCRIPTION
**Pull request by sergenyalcin**
### Description of your changes

Remove family provider migrator docs because they moved to the new repo

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by jeanduplessis — APPROVED** [review]

**Review by ulucinar — APPROVED** [review]
Thanks @sergenyalcin, lgtm. I think we have already announced the migration docs in this repository and we will need to sync with the community so that they can find the new place for the documentation after the other docs are published and this is merged.

**Comment by jeanduplessis** [comment]
> Thanks @sergenyalcin, lgtm. I think we have already announced the migration docs in this repository and we will need to sync with the community so that they can find the new place for the documentation after the other docs are published and this is merged.

@ulucinar the only places we communicated this to the community are:
- https://docs.google.com/document/d/1tmXi3CRhCKNvdDTApzfNsBIFF88qhpUQth3t5y5oKew/edit
- https://crossplane.slack.com/archives/C056YAQRV16

I can take the action to make the necessary updates to link to the new location.

**Comment by ytsarev** [comment]
Please mention the new location here :)

**Comment by jeanduplessis** [comment]
https://github.com/upbound/extensions-migration/tree/main/docs

**Pull request merged**
